{
 "title": "CTA Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval])) / sum(machine_cpu_cores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(machine_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable",
     "legendFormat": "deployment/{{namespace}}/{{deployment}}"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable",
     "legendFormat": "daemonset/{{namespace}}/{{daemonset}}"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (node) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on (node) group_left sum by (node) (irate(node_cpu_seconds_total[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Most CPU-Intensive pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(5, sum by(namespace, pod) (irate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) / on (namespace, pod) group_left sum by (namespace, pod) (kube_pod_container_resource_limits{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Most CPU-Intensive pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(5, sum by (namespace, pod) (container_memory_working_set_bytes{container!=\"\"}) / on (namespace, pod) group_left sum by (namespace, pod) (kube_pod_container_resource_limits{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Perf Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total[2m])), 0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress ResponseTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_bucket[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "POD Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (destination_service_name) (istio_requests_total{response_code!~\"5.*\"}) / sum by (destination_service_name) (istio_requests_total)",
       "legendFormat": "{{destination_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Monitoring(istio-system)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container!=\"\", namespace=\"istio-system\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\", namespace=\"istio-system\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Monitoring(default)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container!=\"\", namespace=\"default\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\", namespace=\"default\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}